doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                prefix: 'Users\Entity'