parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Users\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Users\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Users\Service\UserManager:
        class: Users\Service\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"