Users\Entity\Attribute:
  type: entity
  table: attribute
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      length: 255

  indexes:
    attribute_name_index:
      columns: ["title"]